apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-pod
  template:
    metadata:
      labels:
        app: multi-pod
    spec:
      containers:
        - name: frontend-container
          image: nginx
          volumeMounts:
            - name: shared-data
              mountPath: /usr/share/nginx/html
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
        - name: data-container
          image: thugpigeon653/lneilsen-demo:latest
          volumeMounts:
            - name: shared-data
              mountPath: /pod-data
          command: ["/bin/sh"]
          args: ["-c", "python app.py"]
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.25"
              memory: "256Mi"
      volumes:
        - name: shared-data
          emptyDir: {}
