apiVersion: v1
kind: Service
metadata:
  name: multi-pod-service
spec:
  restartPolicy: Never
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000  
  selector:
    app: multi-pod
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: frontend-container
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      resources:
        limits:
          cpu: "0.5"  
          memory: "512Mi" 
        requests:
          cpu: "0.25"
          memory: "256Mi"  

    - name: data-container
      image: thugpigeon653/lneilsen-demo:latest
      volumeMounts:
        - name: shared-data
          mountPath: /pod-data
      command: ["/bin/sh"]
      args: ["-c", "python app.py"]
      resources:
        limits:
          cpu: "0.5"  
          memory: "512Mi" 
        requests:
          cpu: "0.25"
          memory: "256Mi"
